### ISSUE TITLE
如何开启jupyterlab？

### ISSUE THREAD

**Issue by weinformatics** [dclong/docker-jupyterhub-julia#1]
您好，我用该镜像之后，打开的界面没有jupyterlab，请问如何启动？
```
docker run -p 8000:8000 -d --name jupyterhub dclong/jupyterhub-julia jupyterhub

```

**Comment by dclong** [comment]
@weinformatics It sounds like that you have already figured it out. The instruction on how to use the Docker images can be found in the readme file. 

BTW, I just update the Julia image.
